election_label: SF_20101102
election_name: San Francisco November 2, 2010 Consolidated Statewide Direct Primary Election
master_file_glob: Master*.txt
ballot_file_glob: Ballot*.txt
contests:
 - label: D10
   url: http://sfelections.org/results/20101102/data/D10.zip
   winner: MALIA COHEN
   finalists:
    - TONY KELLY
