#
# This file is UTF-8 encoded.
#
election_label: SF_2006-11-07
election_name: "San Francisco November 7, 2006 Consolidated General Election"
source: data/RcvCalcInput/2006/
master_file_glob: "*Master*.txt"
ballot_file_glob: "*Ballot_*.txt"
contests:
 - label: D2
   source: D02
   winner: ERIC MAR
   finalists:
    - SUE LEE
 - label: D3
   url: http://www.sfgov2.org/ftp/uploadedfiles/elections/ElectionsArchives/2008/november/D3_BallotImageFinal.zip
   winner: DAVID CHIU
   finalists:
    - "JOSEPH ALIOTO, JR."
 - label: D4
   url: http://www.sfgov2.org/ftp/uploadedfiles/elections/ElectionsArchives/2008/november/D4_BallotImageFinal.zip
   winner: CARMEN CHU
   finalists:
 - label: D9
   url: http://www.sfgov2.org/ftp/uploadedfiles/elections/ElectionsArchives/2008/november/D9_BallotImageFinal.zip
   winner: DAVID CAMPOS
   finalists:
    - MARK SANCHEZ
 - label: D11
   url: http://www.sfgov2.org/ftp/uploadedfiles/elections/ElectionsArchives/2008/november/D11_BallotImageFinal.zip
   winner: JOHN AVALOS
   finalists:
    - AHSHA SAFAI
